### ISSUE TITLE
Upgrade satosa

### ISSUE THREAD

**Issue by c00kiemon5ter** [SUNET/docker-satosa#30]
There is a new release - version `8.3.0`.

**Comment by c00kiemon5ter** [comment]
With this release we have support for enforcing scope checking.

To do that, the `attribute_modifications.FilterAttributeValues` plugin must be configured.

An example file can be found here:
https://github.com/IdentityPython/SATOSA/blob/master/example/plugins/microservices/filter_attributes.yaml.example

For us that would look like
```yaml
---
satosa_config:
   value_scope_check: "/etc/satosa/value_scope_check.yaml"
   ...
...
value_scope_check:
   module: satosa.micro_services.attribute_generation.AddSyntheticAttributes
   plugin: AddSyntheticAttributes
   name: AddSyntheticAttributes
   config:
      attribute_filters:
        "":
          "":
            eduPersonAffiliation: "^(faculty|student|staff|alum|member|affiliate|employee|library-walk-in)$"
            eduPersonPrimaryAffiliation: "^(faculty|student|staff|alum|member|affiliate|employee|library-walk-in)$"
            eduPersonScopedAffiliation:
              regexp: "^(faculty|student|staff|alum|member|affiliate|employee|library-walk-in)@"
                shibmdscope_match_scope:
            eduPersonPrincipalName:
              shibmdscope_match_scope:
            subject-id:
              regexp: "^[0-9A-Za-z][-=0-9A-Za-z]{0,126}@[0-9A-Za-z][-.0-9A-Za-z]{0,126}\\Z"
              shibmdscope_match_scope:
            pairwise-id:
              regexp: "^[0-9A-Za-z][-=0-9A-Za-z]{0,126}@[0-9A-Za-z][-.0-9A-Za-z]{0,126}\\Z"
              shibmdscope_match_scope:
            schacHomeOrganization:
              shibmdscope_match_value:
```

meaning that we check
- the syntax of the values of eduPersonAffiliation, eduPersonPrimaryAffiliation, eduPersonScopedAffiliation, subject-id and pairwise-id
- and the scope for eduPersonScopedAffiliation, eduPersonPrincipalName, subject-id, pairwise-id and schacHomeOrganization

---

This should be tested, and then steadily rolled out to our proxies.
